name: 'Terraform Pull Request'
description: 'Performs terraform init, fmt, validate, and plan'

inputs:
  terraform_directory:
    description: 'The directory containing the Terraform files'
    required: true
  config_directory:
    description: 'The directory containing the configuration files (backend and vars)'
    required: true
  secrets:
    description: 'Newline-separated list of secrets or env vars to export (e.g., KEY=VALUE)'
    required: false
    default: ''
  github_token:
    description: 'GitHub token for posting comments'
    required: true

runs:
  using: "composite"
  steps:
    - name: Export Secrets
      shell: bash
      run: |
        if [ -n "${{ inputs.secrets }}" ]; then
          echo "${{ inputs.secrets }}" >> "$GITHUB_ENV"
        fi

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.13.5"

    - name: Terraform Init
      shell: bash
      working-directory: ${{ inputs.terraform_directory }}
      run: |
        terraform init \
          -backend-config="${{ github.workspace }}/${{ inputs.config_directory }}/terraform.tfbackend"

    - name: Terraform Format
      shell: bash
      working-directory: ${{ inputs.terraform_directory }}
      run: terraform fmt -check

    - name: Terraform Validate
      shell: bash
      working-directory: ${{ inputs.terraform_directory }}
      run: terraform validate

    - name: Terraform Plan
      id: plan
      shell: bash
      working-directory: ${{ inputs.terraform_directory }}
      run: |
        terraform plan \
          -var-file="${{ github.workspace }}/${{ inputs.config_directory }}/terraform.tfvars" \
          -lock=false \
          -no-color \
          -out=tfplan.binary
        terraform show -no-color tfplan.binary > tfplan.txt
        
    - name: Post Terraform Plan Comment
      uses: actions/github-script@v7
      with:
        github-token: ${{ inputs.github_token }}
        script: |
          const fs = require('fs');
          const path = require('path');
          
          // GitHub comment size limit (with buffer for formatting)
          const MAX_COMMENT_LENGTH = 65000;
          
          const planPath = path.join('${{ github.workspace }}', '${{ inputs.terraform_directory }}', 'tfplan.txt');
          const plan = fs.readFileSync(planPath, 'utf8');
          const truncatedPlan = plan.length > MAX_COMMENT_LENGTH 
            ? plan.substring(0, MAX_COMMENT_LENGTH) + '\n\n... (output truncated due to length)' 
            : plan;
          
          const output = `### Terraform Plan for \`${{ inputs.terraform_directory }}\`
          
          <details>
          <summary>Show Plan</summary>
          
          \`\`\`hcl
          ${truncatedPlan}
          \`\`\`
          
          </details>
          
          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ inputs.terraform_directory }}\`, Workflow: \`${{ github.workflow }}\`*`;
          
          try {
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });
            console.log('Successfully posted Terraform plan comment');
          } catch (error) {
            core.setFailed(`Failed to post comment: ${error.message}`);
            throw error;
          }
