name: 'Backend Pull Request'
description: 'Lints, tests, and builds the backend service'

runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: services/backend/go.mod
        cache-dependency-path: services/backend/go.sum

    - name: Install dependencies
      shell: bash
      working-directory: services/backend
      run: |
        make install

    - name: Lint
      shell: bash
      working-directory: services/backend
      run: |
        make lint

    - name: Test
      shell: bash
      working-directory: services/backend
      run: |
        make test

    - name: Build Docker image
      shell: bash
      working-directory: services/backend
      run: |
        docker build \
          -t web-app-demo-backend:${{ github.sha }} \
          .
